# Extends the base docker-compose.yml file.
# Services with the same name will be merged.

version: "3.5"

services:
    proxy:
        build:
            args:
                - CONTAINER_NAME_UI
                - UI_PORT
            dockerfile: ./packages/proxy/310.dockerfile
        depends_on:
            - reference_ui
    geolocation:
        image: cpsc310geocoder
        container_name: ${CONTAINER_NAME_GEO}
        ports:
            - ${GEO_PORT}:${GEO_PORT}
        restart: always
        user: "${UID}"
    reference_ui:
        image: cpsc310reference_ui
        container_name: ${CONTAINER_NAME_UI}
	environment:
            - PLATFROM
        expose:
            - ${UI_PORT}
        restart: always
        user: "${UID}"

